# Generated by Django 4.1.4 on 2022-12-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('noticia_choice', models.CharField(blank=True, choices=[('Cafayate', 'Cafayate'), ('Policiales', 'Policiales'), ('Deportes', 'Deportes'), ('Clasificados', 'Clasificados')], default='d', help_text='Seccion de Noticia', max_length=50)),
            ],
        ),
    ]
