# Generated by Django 4.1.4 on 2022-12-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compraEnCafa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
