# Generated by Django 4.1.4 on 2023-01-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraEnCafa', '0002_rename_noticias_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descripcion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_choice',
            field=models.CharField(blank=True, choices=[('Cafayate', 'Cafayate'), ('Policiales', 'Policiales'), ('Deportes', 'Deportes'), ('Clasificados', 'Clasificados'), ('Vacaciones', 'Vacaciones'), ('Salud', 'Salud'), ('Tecnología', 'Tecnología')], default='d', help_text='Seccion de Noticia', max_length=50),
        ),
    ]
