# Generated by Django 4.1.4 on 2023-01-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraEnCafa', '0003_noticia_descripcion_alter_noticia_noticia_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='comentarios',
            field=models.CharField(default='', max_length=400),
        ),
    ]
