# Generated by Django 4.1.4 on 2023-01-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraEnCafa', '0004_negocio_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(default='', max_length=400)),
                ('usuario_choice', models.CharField(blank=True, choices=[('Quiero comprar', 'Cliente'), ('Quiero vender', 'Comerciante')], default='d', help_text='Seccion de Noticia', max_length=50)),
            ],
        ),
    ]
