# Generated by Django 4.1.4 on 2023-01-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraEnCafa', '0007_noticia_imageportada_alter_usuario_usuario_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagePortada',
            field=models.FilePathField(path='/img'),
        ),
    ]
