# Generated by Django 4.1.2 on 2022-11-11 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idioma', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID idioma', primary_key=True, serialize=False)),
                ('idioma_choice', models.CharField(blank=True, choices=[('esp', 'Español'), ('eng', 'Ingles'), ('por', 'Portugues'), ('jap', 'Japones')], default='d', help_text='Idioma', max_length=4)),
            ],
        ),
    ]
